services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
      - ./db_data/init:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "1234:5432"
    